### ISSUE TITLE
Support deletion of cask formula

### ISSUE THREAD

**Issue by kdeldycke** [kdeldycke/meta-package-manager#17]
See the case of Audacity at: https://github.com/matryer/bitbar-plugins/issues/493#issuecomment-234276654

The error we get from `mpm` is kind of cryptic:
![screen shot 2016-12-22 at 00 03 06](https://cloud.githubusercontent.com/assets/159718/21409389/469910f8-c7da-11e6-9e6b-eec406553de8.png)

This case might be detectable. See the `(!)` flag `cask` is reporing:
```
$ brew cask list
atom                                   hexchat                                quicklook-json
audacity (!)                           hugin                                  rowanj-gitx
avidemux                               inkscape                               spectacle

$ brew cask list --versions
android-file-transfer latest
atom 1.12.6
audacity (!) 2.1.2
avidemux 2.6.15
bitbar 1.9.2

$ brew cask info audacity
audacity: 
/usr/local/Caskroom/audacity/2.1.2 (1.3M)
Error: Invalid tap name '/'
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/tap.rb:29:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:55:in `repo_info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:23:in `info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:11:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:7:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:7:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:110:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by kdeldycke** [comment]
I haven't encountered this issue in 5 years. I guess homebrew is now gracefully managing that case. Let's close this.
