### ISSUE TITLE
No support of Cask packages with multiple names

### ISSUE THREAD

**Issue by rkrug** [kdeldycke/meta-package-manager#26]
Hi 

I get the following error

mpm version: 2.2.0, installed via 
```
pip install meta-package-mager
```

```
09:59:46 ~$ mpm -m cask -v DEBUG outdated
debug: Verbosity set to DEBUG.
debug: Raw platform ID: darwin.
debug: Running `/usr/local/bin/brew cask --version`...
Sync cask package info...
debug: Running `/usr/local/bin/brew cask update`...
debug: Running `/usr/local/bin/brew cask list --versions`...
debug: Running `/usr/local/bin/brew cask info alfred`...
debug: Running `/usr/local/bin/brew cask info appcleaner`...
debug: Running `/usr/local/bin/brew cask info avidemux`...
debug: Running `/usr/local/bin/brew cask info back-in-time`...
debug: Running `/usr/local/bin/brew cask info backuploupe`...
debug: Running `/usr/local/bin/brew cask info bettertouchtool`...
debug: Running `/usr/local/bin/brew cask info bitbar`...
debug: Running `/usr/local/bin/brew cask info box-sync`...
debug: Running `/usr/local/bin/brew cask info burn`...
debug: Running `/usr/local/bin/brew cask info calibre`...
debug: Running `/usr/local/bin/brew cask info dash`...
debug: Running `/usr/local/bin/brew cask info deeper`...
debug: Running `/usr/local/bin/brew cask info diffmerge`...
debug: Running `/usr/local/bin/brew cask info docker`...
debug: Running `/usr/local/bin/brew cask info dropbox`...
debug: Running `/usr/local/bin/brew cask info dupeguru-me`...
debug: Running `/usr/local/bin/brew cask info endnote`...
debug: Running `/usr/local/bin/brew cask info file-juicer`...
debug: Running `/usr/local/bin/brew cask info filebot`...
debug: Running `/usr/local/bin/brew cask info firefox-beta`...
debug: Running `/usr/local/bin/brew cask info fluid`...
debug: Running `/usr/local/bin/brew cask info flux`...
debug: Running `/usr/local/bin/brew cask info fork`...
debug: Running `/usr/local/bin/brew cask info free-ruler`...
debug: Running `/usr/local/bin/brew cask info github-desktop`...
debug: Running `/usr/local/bin/brew cask info gitx`...
debug: Running `/usr/local/bin/brew cask info google-drive`...
debug: Running `/usr/local/bin/brew cask info google-earth`...
debug: Running `/usr/local/bin/brew cask info gpgtools`...
debug: Running `/usr/local/bin/brew cask info gramps`...
debug: Running `/usr/local/bin/brew cask info grandperspective`...
debug: Running `/usr/local/bin/brew cask info handbrake`...
debug: Running `/usr/local/bin/brew cask info istumbler`...
debug: Running `/usr/local/bin/brew cask info iterm2`...
debug: Running `/usr/local/bin/brew cask info iterm2-beta`...
debug: Running `/usr/local/bin/brew cask info jabref`...
debug: Running `/usr/local/bin/brew cask info java`...
debug: Running `/usr/local/bin/brew cask info karabiner`...
debug: Running `/usr/local/bin/brew cask info keepingyouawake`...
debug: Running `/usr/local/bin/brew cask info kitematic`...
debug: Running `/usr/local/bin/brew cask info lastpass`...
debug: Running `/usr/local/bin/brew cask info launchcontrol`...
debug: Running `/usr/local/bin/brew cask info libreoffice`...
debug: Running `/usr/local/bin/brew cask info lilypond`...
debug: Running `/usr/local/bin/brew cask info lingon-x`...
debug: Running `/usr/local/bin/brew cask info lyx`...
debug: Running `/usr/local/bin/brew cask info mactex`...
debug: Running `/usr/local/bin/brew cask info maintenance`...
debug: Running `/usr/local/bin/brew cask info makemkv`...
debug: Running `/usr/local/bin/brew cask info max`...
debug: Running `/usr/local/bin/brew cask info mediaelch`...
debug: Running `/usr/local/bin/brew cask info mendeley-desktop`...
debug: Running `/usr/local/bin/brew cask info metadatics`...
debug: Running `/usr/local/bin/brew cask info mkvtools`...
debug: Running `/usr/local/bin/brew cask info musicbrainz-picard`...
debug: Running `/usr/local/bin/brew cask info namechanger`...
debug: Running `/usr/local/bin/brew cask info omnidisksweeper`...
debug: Running `/usr/local/bin/brew cask info onyx`...
debug: Running `/usr/local/bin/brew cask info opera-beta`...
debug: Running `/usr/local/bin/brew cask info platypus`...
debug: Running `/usr/local/bin/brew cask info playonmac`...
debug: Running `/usr/local/bin/brew cask info plex-media-player`...
debug: Running `/usr/local/bin/brew cask info r-app`...
debug: Running `/usr/local/bin/brew cask info renamer`...
debug: Running `/usr/local/bin/brew cask info rstudio`...
debug: Running `/usr/local/bin/brew cask info scribus`...
debug: Running `/usr/local/bin/brew cask info sdformatter`...
debug: Running `/usr/local/bin/brew cask info serial`...
debug: Running `/usr/local/bin/brew cask info skim`...
debug: Running `/usr/local/bin/brew cask info skype`...
debug: Running `/usr/local/bin/brew cask info sourcetree`...
debug: Running `/usr/local/bin/brew cask info spideroakone`...
debug: Running `/usr/local/bin/brew cask info spotify`...
debug: Running `/usr/local/bin/brew cask info tag`...
debug: Running `/usr/local/bin/brew cask info teamviewer`...
debug: Running `/usr/local/bin/brew cask info textmate`...
debug: Running `/usr/local/bin/brew cask info the-unarchiver`...
debug: Running `/usr/local/bin/brew cask info thunderbird`...
debug: Running `/usr/local/bin/brew cask info torbrowser`...
debug: Running `/usr/local/bin/brew cask info virtualbox`...
debug: Running `/usr/local/bin/brew cask info vlc`...
debug: Running `/usr/local/bin/brew cask info vox`...
debug: Running `/usr/local/bin/brew cask info wordpresscom`...
debug: Running `/usr/local/bin/brew cask info xbench`...
debug: Running `/usr/local/bin/brew cask info xld`...
Traceback (most recent call last):
  File "/usr/local/bin/mpm", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/meta_package_manager/cli.py", line 193, in outdated
    manager.sync()
  File "/usr/local/lib/python2.7/site-packages/meta_package_manager/managers/homebrew.py", line 249, in sync
    package_name = output.split('==> Name\n')[1].split('\n')[0]
IndexError: list index out of range
10:01:58 ~$ brew cask info xld
xld: 2016.10.07
http://tmkk.undo.jp/xld/index_e.html
/usr/local/Caskroom/xld/2016.10.07 (45 files, 221.6K)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/xld.rb
==> Names
X Lossless Decoder
XLD
==> Artifacts
XLD.app (app)
10:02:19 ~$ mpm --version
mpm, version 2.2.0
10:03:06 ~$
```

**Comment by kdeldycke** [comment]
Good catch! And thanks for the bug report.

Issue is indeed in the `xld` package which is providing multiple names:
```
==> Names
X Lossless Decoder
XLD
```

First time I encounter this construction. Shouldn't be hard to fix. I'll try to find time to address this one in the next release.

**Comment by rkrug** [comment]
Thanks.

**Comment by rkrug** [comment]
Any chance of releasing a bugfix update? I would love to have the bitbar plugin working again...

**Comment by kdeldycke** [comment]
@rkrug : just fixed the issue. I'll probably release a new `mpm` package in the next few days.

**Comment by rkrug** [comment]
Thanks - looking forward to it.
