### ISSUE TITLE
Exception when gem gives no output

### ISSUE THREAD

**Issue by SikhNerd** [kdeldycke/meta-package-manager#29]
`gem outdated` on my system has no output when there are no outdated packages, just a successful exit. Locally I wrapped the[ package loop](https://github.com/kdeldycke/meta-package-manager/blob/develop/meta_package_manager/managers/gem.py#L82-L91) inside an `if output:` block to get past this error.

```
Sync gem package info...
Traceback (most recent call last):
  File "/usr/local/bin/mpm", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/meta_package_manager/cli.py", line 193, in outdated
    manager.sync()
  File "/usr/local/lib/python2.7/site-packages/meta_package_manager/managers/gem.py", line 82, in sync
    for package in output.split('\n'):
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by kdeldycke** [comment]
Thanks @SikhNerd for the report! Just fixed this issue upstream. Will be part of the upcoming `mpm` release.
