### ISSUE TITLE
pip 19.2 AttributeError: 'NoneType' object has no attribute 'is_hash_allowed'

### ISSUE THREAD

**Issue by rogatty** [kdeldycke/meta-package-manager#53]
After upgrading pip to version 19.2 mpm stopped working for python 2.7 and 3.7:
```
mpm --version
mpm, version 2.8.0

pip --version
pip 19.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

pip2 --version
pip 19.2 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)

mpm outdated
...
Sync pip2 package info...
error: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
error: ERROR: Exception:
error: Traceback (most recent call last):
error:   File "/usr/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
error:     status = self.run(options, args)
error:   File "/usr/local/lib/python2.7/site-packages/pip/_internal/commands/list.py", line 156, in run
error:     packages = self.get_outdated(packages, options)
error:   File "/usr/local/lib/python2.7/site-packages/pip/_internal/commands/list.py", line 164, in get_outdated
error:     dist for dist in self.iter_packages_latest_infos(packages, options)
error:   File "/usr/local/lib/python2.7/site-packages/pip/_internal/commands/list.py", line 195, in iter_packages_latest_infos
error:     best_candidate = evaluator.get_best_candidate(all_candidates)
error:   File "/usr/local/lib/python2.7/site-packages/pip/_internal/index.py", line 729, in get_best_candidate
error:     best_candidate = max(candidates, key=self._sort_key)
error:   File "/usr/local/lib/python2.7/site-packages/pip/_internal/index.py", line 710, in _sort_key
error:     has_allowed_hash = int(link.is_hash_allowed(self._hashes))
error:   File "/usr/local/lib/python2.7/site-packages/pip/_internal/models/link.py", line 213, in is_hash_allowed
error:     return hashes.is_hash_allowed(self.hash_name, hex_digest=self.hash)
error: AttributeError: 'NoneType' object has no attribute 'is_hash_allowed'

Sync pip3 package info...
error: ERROR: Exception:
error: Traceback (most recent call last):
error:   File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
error:     status = self.run(options, args)
error:   File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/list.py", line 156, in run
error:     packages = self.get_outdated(packages, options)
error:   File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/list.py", line 164, in get_outdated
error:     dist for dist in self.iter_packages_latest_infos(packages, options)
error:   File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/list.py", line 164, in <listcomp>
error:     dist for dist in self.iter_packages_latest_infos(packages, options)
error:   File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/list.py", line 195, in iter_packages_latest_infos
error:     best_candidate = evaluator.get_best_candidate(all_candidates)
error:   File "/usr/local/lib/python3.7/site-packages/pip/_internal/index.py", line 729, in get_best_candidate
error:     best_candidate = max(candidates, key=self._sort_key)
error:   File "/usr/local/lib/python3.7/site-packages/pip/_internal/index.py", line 710, in _sort_key
error:     has_allowed_hash = int(link.is_hash_allowed(self._hashes))
error:   File "/usr/local/lib/python3.7/site-packages/pip/_internal/models/link.py", line 213, in is_hash_allowed
error:     return hashes.is_hash_allowed(self.hash_name, hex_digest=self.hash)
error: AttributeError: 'NoneType' object has no attribute 'is_hash_allowed'
```

**Comment by kdeldycke** [comment]
That's a Pip issue, resolved a long time ago: https://github.com/pypa/pip/issues/6772
