### ISSUE TITLE
Every mpm command fails with AttributeError: 'NoneType' object has no attribute 'groupdict'

### ISSUE THREAD

**Issue by bit-man** [kdeldycke/meta-package-manager#536]
When executing any `mpm` command fails with

```
$ mpm --all-managers managers
Traceback (most recent call last):
  File "/home/xxxx/.local/bin/mpm", line 8, in <module>
    sys.exit(mpm())
  File "/home/xxxx/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/xxxx/.local/lib/python3.9/site-packages/click_extra/commands.py", line 130, in main
    super().main(*args, **kwargs)
  File "/home/xxxx/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/xxxx/.local/lib/python3.9/site-packages/click_extra/commands.py", line 134, in invoke
    return super().invoke(ctx)
  File "/home/xxxx/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xxxx/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxxx/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/xxxx/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/xxxx/.local/lib/python3.9/site-packages/meta_package_manager/cli.py", line 286, in managers
    version_infos = OK if manager.fresh else KO
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/xxxx/.local/lib/python3.9/site-packages/meta_package_manager/base.py", line 265, in fresh
    if not self.version:
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/xxxx/.local/lib/python3.9/site-packages/meta_package_manager/base.py", line 239, in version
    re.compile(self.version_regex, re.MULTILINE | re.VERBOSE)
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

And some software info

```
$ mpm --version
mpm, version 4.11.0

$ uname -a
Linux xxxx 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

$ pip --version
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)

```

**Comment by kdeldycke** [comment]
Thanks for reporting this issue. Can you share the results of these commands on your system?

```shell-session
$ python -m pip --version
$ python3 -m pip --version
$ mpm --all-managers --verbosity DEBUG managers
```

**Comment by bit-man** [comment]
```
$ python -m pip --version
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3

$ python3 -m pip --version
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)

$ mpm --all-managers --verbosity DEBUG managers
debug: Verbosity set to DEBUG.
debug: Search for configuration in default location...
debug: No default configuration found.
debug: No configuration provided.
debug: apm CLI not found.
debug: apt CLI found at /usr/local/bin/apt
debug: ► /usr/local/bin/apt --version
debug:   apt
debug:   Usage: apt command [options]
debug:          apt help command [options]
debug: 
debug:   Commands:
debug:     add-repository   - Add entries to apt sources.list
debug:     autoclean        - Erase old downloaded archive files
debug:     autopurge        - Remove packages with their configuration files and automatically remove all unused packages
debug:     autoremove       - Remove automatically all unused packages
debug:     build            - Build binary or source packages from sources
debug:     build-dep        - Configure build-dependencies for source packages
debug:     changelog        - View a package's changelog
debug:     check            - Verify that there are no broken dependencies
debug:     clean            - Erase downloaded archive files
debug:     contains         - List packages containing a file
debug:     content          - List files contained in a package
debug:     deb              - Install a .deb package
debug:     depends          - Show raw dependency information for a package
debug:     dist-upgrade     - Upgrade the system by removing/installing/upgrading packages
debug:     download         - Download the .deb file for a package
debug:     edit-sources     - Edit /etc/apt/sources.list with your preferred text editor
debug:     dselect-upgrade  - Follow dselect selections
debug:     full-upgrade     - Same as 'dist-upgrade'
debug:     held             - List all held packages
debug:     help             - Show help for a command
debug:     hold             - Hold a package
debug:     install          - Install/upgrade packages
debug:     list             - List packages based on package names
debug:     policy           - Show policy settings
debug:     purge            - Remove packages and their configuration files
debug:     recommends       - List missing recommended packages for a particular package
debug:     rdepends         - Show reverse dependency information for a package
debug:     reinstall        - Download and (possibly) reinstall a currently installed package
debug:     remove           - Remove packages
debug:     search           - Search for a package by name and/or expression
debug:     show             - Display detailed information about a package
debug:     showhold         - Same as 'held'
debug:     showsrc          - Display all the source package records that match the given package name
debug:     source           - Download source archives
debug:     sources          - Same as 'edit-sources'
debug:     unhold           - Unhold a package
debug:     update           - Download lists of new/upgradable packages
debug:     upgrade          - Perform a safe upgrade
debug:     version          - Show the installed version of a package
debug: Extracted version: Usage:
debug: apt CLI found at /usr/local/bin/apt
debug: ► /usr/local/bin/apt version apt
debug:   2.2.4
Traceback (most recent call last):
  File "/home/bit-man/.local/bin/mpm", line 8, in <module>
    sys.exit(mpm())
  File "/home/bit-man/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/bit-man/.local/lib/python3.9/site-packages/click_extra/commands.py", line 130, in main
    super().main(*args, **kwargs)
  File "/home/bit-man/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/bit-man/.local/lib/python3.9/site-packages/click_extra/commands.py", line 134, in invoke
    return super().invoke(ctx)
  File "/home/bit-man/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bit-man/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bit-man/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/bit-man/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/bit-man/.local/lib/python3.9/site-packages/meta_package_manager/cli.py", line 286, in managers
    version_infos = OK if manager.fresh else KO
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/bit-man/.local/lib/python3.9/site-packages/meta_package_manager/base.py", line 265, in fresh
    if not self.version:
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/bit-man/.local/lib/python3.9/site-packages/meta_package_manager/base.py", line 239, in version
    re.compile(self.version_regex, re.MULTILINE | re.VERBOSE)
AttributeError: 'NoneType' object has no attribute 'groupdict'

```

**Comment by goodevilgenius** [comment]
I have this same issue on macOS.

I just installed it this morning with `python3 -m pip install meta-package-manager`

Here's some output:

```
$ mpm -a managers
error:   The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
error:   Please visit http://www.java.com for information on installing Java.
error:   The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
error:   Please visit http://www.java.com for information on installing Java.
Traceback (most recent call last):
  File "/usr/local/bin/mpm", line 8, in <module>
    sys.exit(mpm())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click_extra/commands.py", line 130, in main
    super().main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click_extra/commands.py", line 134, in invoke
    return super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/meta_package_manager/cli.py", line 286, in managers
    version_infos = OK if manager.fresh else KO
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/meta_package_manager/base.py", line 265, in fresh
    if not self.version:
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/meta_package_manager/base.py", line 239, in version
    re.compile(self.version_regex, re.MULTILINE | re.VERBOSE)
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

```
$ mpm --version
mpm, version 4.11.0
{'username': '-', 'guid': 'bd92d7b5d66e95baac0b0fc36a247a5', 'hostname': '-', 'hostfqdn': '-', 'uname': {'system': 'Darwin', 'node': '-', 'release': '21.3.0', 'version': 'Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64', 'machine': 'x86_64', 'processor': 'i386'}, 'linux_dist_name': '', 'linux_dist_version': '', 'cpu_count': 8, 'fs_encoding': 'utf-8', 'ulimit_soft': 256, 'ulimit_hard': 9223372036854775807, 'cwd': '-', 'umask': '0o2', 'python': {'argv': '-', 'bin': '-', 'version': '3.9.12 (main, Mar 26 2022, 15:51:15) [Clang 13.1.6 (clang-1316.0.21.2)]', 'compiler': 'Clang 13.1.6 (clang-1316.0.21.2)', 'build_date': 'Mar 26 2022 15:51:15', 'version_info': [3, 9, 12, 'final', 0], 'features': {'openssl': 'OpenSSL 1.1.1n  15 Mar 2022', 'expat': 'expat_2.4.1', 'sqlite': '3.38.2', 'tkinter': '', 'zlib': '1.2.11', 'unicode_wide': True, 'readline': True, '64bit': True, 'ipv6': True, 'threading': True, 'urandom': True}}, 'time_utc': '2022-04-04 14:09:17.339140', 'time_utc_offset': -6.0, '_eco_version': '1.0.1'}
```

```
$ uname -a
Darwin smiling-fruit 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
```

```
$ python -m pip --version
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named pip
```

```
$ python3 -m pip --version
pip 22.0.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
```

```
$ mpm --all-managers --verbosity DEBUG managers
debug: Verbosity set to DEBUG.
debug: Search for configuration in default location...
debug: No default configuration found.
debug: No configuration provided.
debug: apm CLI not found.
debug: apt CLI found at /usr/bin/apt
debug: ► /usr/bin/apt --version
error:   The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
error:   Please visit http://www.java.com for information on installing Java.
debug: apt CLI found at /usr/bin/apt
debug: ► /usr/bin/apt version apt
error:   The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
error:   Please visit http://www.java.com for information on installing Java.
debug: brew CLI found at /usr/local/bin/brew
debug: ► /usr/local/bin/brew --version
debug:   Homebrew 3.4.4
debug:   Homebrew/homebrew-core (git revision 5222272d62c; last commit 2022-04-01)
debug:   Homebrew/homebrew-cask (git revision 31060c3207; last commit 2022-04-01)
debug: Extracted version: 3.4.4
debug: brew CLI found at /usr/local/bin/brew
debug: ► /usr/local/bin/brew --version
debug:   Homebrew 3.4.4
debug:   Homebrew/homebrew-core (git revision 5222272d62c; last commit 2022-04-01)
debug:   Homebrew/homebrew-cask (git revision 31060c3207; last commit 2022-04-01)
debug: Extracted version: 3.4.4
debug: choco CLI not found.
debug: composer CLI found at /usr/local/bin/composer
debug: ► /usr/local/bin/composer --version
debug:   Composer 2.3.2 2022-03-30 20:45:25
Traceback (most recent call last):
  File "/usr/local/bin/mpm", line 8, in <module>
    sys.exit(mpm())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click_extra/commands.py", line 130, in main
    super().main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click_extra/commands.py", line 134, in invoke
    return super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/meta_package_manager/cli.py", line 286, in managers
    version_infos = OK if manager.fresh else KO
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/meta_package_manager/base.py", line 265, in fresh
    if not self.version:
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/meta_package_manager/base.py", line 239, in version
    re.compile(self.version_regex, re.MULTILINE | re.VERBOSE)
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

**Comment by kdeldycke** [comment]
I just made a patch to make the version parsing bits more robust. It has been pushed upstream and will be part of `mpm v4.12.0`. I'll make that release right away and should be available on PyPi via `pip` in a couple of minutes.
