### ISSUE TITLE
`OSError: [WinError 193] %1 is not a valid Win32 application`

### ISSUE THREAD

**Issue by jssellars** [kdeldycke/meta-package-manager#542]
Just recently installed mpm, but end up with the error stated in title. Is this just my outdated system or something I'm not catching entirely?

Setup:
- windows 7 - don't laugh!
- python v3.8.10
- pip v22.0.4
- Choco 0.10.15
- npm 6.14.4
- node 13.14.0

Examples

```doscon
C:\Windows\system32>mpm --all-managers managers
```

```pytb
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\mpm.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\click_extra\commands.py", line 130, in main
    super().main(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python38\lib\site-packages\click_extra\commands.py", line 134, in invoke
    return super().invoke(ctx)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\cli.py", line 286, in managers
    version_infos = OK if manager.fresh else KO
  File "C:\Program Files\Python38\lib\functools.py", line 967, in __get__
    val = self.func(instance)
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 266, in fresh
    if not self.version:
  File "C:\Program Files\Python38\lib\functools.py", line 967, in __get__
    val = self.func(instance)
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 230, in version
    output = self.run_cli(
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 464, in run_cli
    output = self.run(*cli, extra_env=extra_env)
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 319, in run
    code, output, error = run_cmd(
  File "C:\Program Files\Python38\lib\site-packages\click_extra\run.py", line 73, in run_cmd
    process = subprocess.run(
  File "C:\Program Files\Python38\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```

```doscon
C:\Windows\system32>mpm installed
warning: Skip unavailable apm manager.
warning: Skip unavailable composer manager.
warning: Skip unavailable gem manager.
```

```pytb
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\mpm.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\click_extra\commands.py", line 130, in main
    super().main(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python38\lib\site-packages\click_extra\commands.py", line 134, in invoke
    return super().invoke(ctx)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\cli.py", line 324, in installed
    for manager in ctx.obj.selected_managers:
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\pool.py", line 184, in select_managers
    if drop_inactive and not manager.available:
  File "C:\Program Files\Python38\lib\functools.py", line 967, in __get__
    val = self.func(instance)
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 288, in available
    return bool(self.supported and self.cli_path and self.executable and self.fresh)
  File "C:\Program Files\Python38\lib\functools.py", line 967, in __get__
    val = self.func(instance)
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 266, in fresh
    if not self.version:
  File "C:\Program Files\Python38\lib\functools.py", line 967, in __get__
    val = self.func(instance)
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 230, in version
    output = self.run_cli(
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 464, in run_cli
    output = self.run(*cli, extra_env=extra_env)
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 319, in run
    code, output, error = run_cmd(
  File "C:\Program Files\Python38\lib\site-packages\click_extra\run.py", line 73, in run_cmd
    process = subprocess.run(
  File "C:\Program Files\Python38\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by kdeldycke** [comment]
Can you share the output of the CLI in `DEBUG` mode like so:

```
C:\Windows\system32> mpm --all-managers --verbosity DEBUG managers
```

**Comment by kdeldycke** [comment]
According https://stackoverflow.com/a/25652030, it seems a file that is suspected by `mpm` to be a package manager is not executable. The `--verbosity DEBUG` option might help us find the culprit.

**Comment by jssellars** [comment]
C:\Windows\system32>mpm --all-managers --verbosity DEBUG managers

> debug: Verbosity set to DEBUG.
> debug: Search for configuration in default location...
> debug: No default configuration found.
> debug: No configuration provided.
> debug: apm CLI not found.
> debug: apt CLI not found.
> debug: apt CLI not found.
> debug: brew CLI not found.
> debug: brew CLI not found.
> debug: choco CLI found at C:\ProgramData\chocolatey\bin\choco.EXE
> debug: ► C:\ProgramData\chocolatey\bin\choco.EXE --version
> debug:   0.10.15
> debug: Extracted version: 0.10.15
> debug: composer CLI not found.
> debug: dnf CLI not found.
> debug: yum CLI not found.
> debug: flatpak CLI not found.
> debug: gem CLI not found.
> debug: mas CLI not found.
> debug: npm CLI found at C:\Program Files\nodejs\npm.CMD
> debug: ► C:\Program Files\nodejs\npm.CMD --version
> debug:   6.14.4
> debug: Extracted version: 6.14.4
> debug: opkg CLI not found.
> debug: python3 CLI not found.
> debug: python CLI found at C:\Program Files\Python38\python.EXE
> debug: ► C:\Program Files\Python38\python.EXE -m pip --no-color --version
> debug:   pip 22.0.4 from C:\Program Files\Python38\lib\site-packages\pip (python 3.8)
> debug: Extracted version: 22.0.4
> debug: snap CLI not found.
> debug: code CLI found at C:\Program Files\Python38\Lib\code.PY
> debug: ► C:\Program Files\Python38\Lib\code.PY --version
> Traceback (most recent call last):
>   File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Program Files\Python38\Scripts\mpm.exe\__main__.py", line 7, in <module>
>   File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Program Files\Python38\lib\site-packages\click_extra\commands.py", line 130, in main
>     super().main(*args, **kwargs)
>   File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "C:\Program Files\Python38\lib\site-packages\click_extra\commands.py", line 134, in invoke
>     return super().invoke(ctx)
>   File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "C:\Program Files\Python38\lib\site-packages\click\decorators.py", line 26, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\cli.py", line 286, in managers
>     version_infos = OK if manager.fresh else KO
>   File "C:\Program Files\Python38\lib\functools.py", line 967, in __get__
>     val = self.func(instance)
>   File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 266, in fresh
>     if not self.version:
>   File "C:\Program Files\Python38\lib\functools.py", line 967, in __get__
>     val = self.func(instance)
>   File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 230, in version
>     output = self.run_cli(
>   File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 464, in run_cli
>     output = self.run(*cli, extra_env=extra_env)
>   File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 319, in run
>     code, output, error = run_cmd(
>   File "C:\Program Files\Python38\lib\site-packages\click_extra\run.py", line 73, in run_cmd
>     process = subprocess.run(
>   File "C:\Program Files\Python38\lib\subprocess.py", line 493, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "C:\Program Files\Python38\lib\subprocess.py", line 858, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Program Files\Python38\lib\subprocess.py", line 1311, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by jssellars** [comment]
I can confirm it works on my Windows 10 environment without any issues. When I get home this evening, I'll toss it at my Win7 system. Don't laugh.... I'm just lazy at the house....

**Comment by jssellars** [comment]
Still not working in Windows 7. I'd say this is likely the problem of having an unsupported OS. I just upgraded to 4.12 and still giving issue. 

C:\Windows\system32> mpm --all-managers --verbosity DEBUG managers
debug: Verbosity set to DEBUG.
debug: Search for configuration in default location...
debug: No default configuration found.
debug: No configuration provided.
debug: apm CLI not found.
debug: apt CLI not found.
debug: apt CLI not found.
debug: brew CLI not found.
debug: brew CLI not found.
debug: choco CLI found at C:\ProgramData\chocolatey\bin\choco.EXE
debug: ► C:\ProgramData\chocolatey\bin\choco.EXE --version
debug:   0.10.15
debug: Extracted version: 0.10.15
debug: composer CLI not found.
debug: dnf CLI not found.
debug: yum CLI not found.
debug: flatpak CLI not found.
debug: gem CLI not found.
debug: mas CLI not found.
debug: npm CLI found at C:\Program Files\nodejs\npm.CMD
debug: ► C:\Program Files\nodejs\npm.CMD --version
debug:   6.14.4
debug: Extracted version: 6.14.4
debug: opkg CLI not found.
debug: python3 CLI not found.
debug: python CLI found at C:\Program Files\Python38\python.EXE
debug: ► C:\Program Files\Python38\python.EXE -m pip --no-color --version
debug:   pip 22.0.4 from C:\Program Files\Python38\lib\site-packages\pip (python 3.8)
debug: Extracted version: 22.0.4
debug: snap CLI not found.
debug: code CLI found at C:\Program Files\Python38\Lib\code.PY
debug: ► C:\Program Files\Python38\Lib\code.PY --version
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\mpm.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\click_extra\commands.py", line 130, in main
    super().main(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python38\lib\site-packages\click_extra\commands.py", line 134, in invoke
    return super().invoke(ctx)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\cli.py", line 286, in managers
    version_infos = OK if manager.fresh else KO
  File "C:\Program Files\Python38\lib\functools.py", line 967, in __get__
    val = self.func(instance)
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 266, in fresh
    if not self.version:
  File "C:\Program Files\Python38\lib\functools.py", line 967, in __get__
    val = self.func(instance)
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 230, in version
    output = self.run_cli(
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 464, in run_cli
    output = self.run(*cli, extra_env=extra_env)
  File "C:\Program Files\Python38\lib\site-packages\meta_package_manager\base.py", line 319, in run
    code, output, error = run_cmd(
  File "C:\Program Files\Python38\lib\site-packages\click_extra\run.py", line 73, in run_cmd
    process = subprocess.run(
  File "C:\Program Files\Python38\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by kdeldycke** [comment]
The fix was in `v4.12.1` are you certain you are running this version? What's the output of `mpm --version`?

**Comment by kdeldycke** [comment]
OK there was an issue with the release process and `v4.12.1` did not reached PyPi. I re-ran the release job. Should be available in a couple of minutes.

**Comment by kdeldycke** [comment]
`v4.12.1` is now available on PyPi: https://pypi.org/project/meta-package-manager/4.12.1/

**Comment by jssellars** [comment]
Confirmed, works like a champ on Windows 7


C:\Windows\system32>mpm --all-managers --verbosity DEBUG managers
debug: Verbosity set to DEBUG.
debug: Search for configuration in default location...
debug: No default configuration found.
debug: No configuration provided.
debug: apm CLI not found.
debug: apt CLI not found.
debug: apt CLI not found.
debug: brew CLI not found.
debug: brew CLI not found.
debug: choco CLI found at C:\ProgramData\chocolatey\bin\choco.EXE
debug: ► C:\ProgramData\chocolatey\bin\choco.EXE --version
debug:   0.10.15
debug: Extracted version: 0.10.15
debug: composer CLI not found.
debug: dnf CLI not found.
debug: yum CLI not found.
debug: flatpak CLI not found.
debug: gem CLI not found.
debug: mas CLI not found.
debug: npm CLI found at C:\Program Files\nodejs\npm.CMD
debug: ► C:\Program Files\nodejs\npm.CMD --version
debug:   6.14.4
debug: Extracted version: 6.14.4
debug: opkg CLI not found.
debug: python3 CLI not found.
debug: python CLI found at C:\Program Files\Python38\python.EXE
debug: ► C:\Program Files\Python38\python.EXE -m pip --no-color --version
debug:   pip 22.0.4 from C:\Program Files\Python38\lib\site-packages\pip (python 3.8)
debug: Extracted version: 22.0.4
debug: snap CLI not found.
debug: code CLI found at C:\Program Files\Python38\Lib\code.PY
debug: ► C:\Program Files\Python38\Lib\code.PY --version
debug: C:\Program Files\Python38\Lib\code.PY is not a valid Windows application.
debug: yarn CLI not found.
?────────────────────┬──────────┬─────────────────────┬───────────────────────────────────────────┬────────────┬───────────?
│ ←[1mPackage manager←[0m    │ ←[1mID←[0m       │ ←[1mSupported←[0m           │ ←[1mCLI←[0m                                       │ ←[1mExecutable←
 │ ←[1mVersion←[0m   │
├────────────────────┼──────────┼─────────────────────┼───────────────────────────────────────────┼────────────┼───────────┤
│ Atom's apm         │ ←[31mapm←[0m      │ ←[32m√←[0m                   │ ←[31m?←[0m apm not found                           │            │
│
│ APT                │ ←[31mapt←[0m      │ ←[31m?←[0m Linux only        │ ←[31m?←[0m apt not found                           │            │
│
│ Linux Mint's apt   │ ←[31mapt-mint←[0m │ ←[31m?←[0m Linux only        │ ←[31m?←[0m apt not found                           │            │
│
│ Homebrew Formulae  │ ←[31mbrew←[0m     │ ←[31m?←[0m Linux, macOS only │ ←[31m?←[0m brew not found                          │            │
│
│ Homebrew Cask      │ ←[31mcask←[0m     │ ←[31m?←[0m macOS only        │ ←[31m?←[0m brew not found                          │            │
│
│ Chocolatey         │ ←[32mchoco←[0m    │ ←[32m√←[0m                   │ ←[32m√←[0m C:\ProgramData\chocolatey\bin\choco.EXE │ ←[32m√←[0m
[32m√←[0m 0.10.15 │
│ PHP's Composer     │ ←[31mcomposer←[0m │ ←[32m√←[0m                   │ ←[31m?←[0m composer not found                      │            │
│
│ DNF                │ ←[31mdnf←[0m      │ ←[31m?←[0m Linux only        │ ←[31m?←[0m dnf, yum not found                      │            │
│
│ Flatpak            │ ←[31mflatpak←[0m  │ ←[31m?←[0m Linux only        │ ←[31m?←[0m flatpak not found                       │            │
│
│ Ruby Gems          │ ←[31mgem←[0m      │ ←[32m√←[0m                   │ ←[31m?←[0m gem not found                           │            │
│
│ Mac AppStore       │ ←[31mmas←[0m      │ ←[31m?←[0m macOS only        │ ←[31m?←[0m mas not found                           │            │
│
│ Node's npm         │ ←[32mnpm←[0m      │ ←[32m√←[0m                   │ ←[32m√←[0m C:\Program Files\nodejs\npm.CMD         │ ←[32m√←[0m
[32m√←[0m 6.14.4  │
│ OPKG               │ ←[31mopkg←[0m     │ ←[31m?←[0m Linux only        │ ←[31m?←[0m opkg not found                          │            │
│
│ Pip                │ ←[32mpip←[0m      │ ←[32m√←[0m                   │ ←[32m√←[0m C:\Program Files\Python38\python.EXE    │ ←[32m√←[0m
[32m√←[0m 22.0.4  │
│ Snap               │ ←[31msnap←[0m     │ ←[31m?←[0m Linux only        │ ←[31m?←[0m snap not found                          │            │
│
│ Visual Studio Code │ ←[31mvscode←[0m   │ ←[32m√←[0m                   │ ←[32m√←[0m C:\Program Files\Python38\Lib\code.PY   │            │ ←[31m?←
         │
│ Node's yarn        │ ←[31myarn←[0m     │ ←[32m√←[0m                   │ ←[31m?←[0m yarn not found                          │            │
│
?────────────────────┴──────────┴─────────────────────┴───────────────────────────────────────────┴────────────┴───────────?
